<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%worker_sector}}`.
 */
class m221221_070337_create_worker_sector_table extends \console\models\CreateTableMigration
{
    public function getTableName()
    {
        return "worker_sector";
    }

    public function columns()
    {
        return [
            'worker_id' => $this->foreignKey("worker", 'id', $this->integer()->notNull()),
            'sector_id'     => $this->foreignKey("sector", 'id', $this->integer()->notNull()),
        ];
    }

    public function safeUp()
    {
        parent::safeUp(); // TODO: Change the autogenerated stub
        $this->createIndex('idx_worker_sector_unq','worker_sector',['worker_id','sector_id'], true);
    }
}
