<?php

/**
 * Handles the creation of table `{{%technician_sector}}`.
 */
class m221107_084335_create_technician_sector_table extends \console\models\CreateTableMigration
{
    public function getTableName()
    {
        return "technician_sector";
    }

    public function columns()
    {
        return [
            'technician_id' => $this->foreignKey("technician", 'id', $this->integer()->notNull()),
            'sector_id'     => $this->foreignKey("sector", 'id', $this->integer()->notNull()),
        ];
    }

    public function safeUp()
    {
        parent::safeUp(); // TODO: Change the autogenerated stub
        $this->createIndex('idx_technician_sector_unq','technician_sector',['technician_id','sector_id'], true);
    }
}
