<?php


namespace common\widgets\dashboard;


use yii\base\Widget;

class AjaxModal extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render("ajax-modal");
    }
}